spring.application.name=GymManagementApp

spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database = Gym

#spring.main.allow-circular-references = true

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.beans.factory=DEBUG
